---
- name: "ensure curl is installed"
  apt:
    name: "curl"
    state: "latest"

- name: "install git"
  apt:
    name: "git"
    default_release: "{{ ansible_distribution_release }}-backports"
    state: "latest"

- name: "create {{ webserver_nginx_content_directory }} directory"
  file:
    path: "{{ webserver_nginx_content_directory }}"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    mode: "0755"
    state: "directory"

- name: "clone KeeWeb"
  git:
    repo: "https://github.com/keeweb/keeweb.git"
    dest: "{{ webserver_nginx_content_directory }}/keeweb"
    version: "gh-pages"
  register: keeweb_repo

- name: "ensure {{ webserver_nginx_content_directory }}/keeweb permissions are set"
  file:
    path: "{{ webserver_nginx_content_directory }}/keeweb"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    state: "directory"
    recurse: yes
  when: keeweb_repo is defined and keeweb_repo.changed

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "keeweb.conf"
    credentials:
      - "htpasswd.keeweb"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "keeweb"
