---
- name: "install git"
  apt:
    name: "git"
    state: "latest"

- name: "create {{ nginx_content_directory }} directory"
  file:
    path: "{{ nginx_content_directory }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0600"
    state: "directory"

- name: "clone KeeWeb"
  git:
    repo: "https://github.com/keeweb/keeweb.git"
    dest: "{{ nginx_content_directory }}/keeweb"

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "keeweb.conf"
    credentials: "htpasswd.keeweb"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "keeweb"
