---
general_scripts_directory: "/usr/local/bin"

nginx_user: "nginx"
nginx_config_directory: "/etc/nginx"
nginx_log_directory: "/var/log/nginx"
nginx_content_directory: "/var/www"
nginx_pidfile: "/var/run/nginx.pid"

letsencrypt_config_directory: "/etc/letsencrypt"

monit_directory: "/etc/monit"
monit_logfile: "/var/log/monit.log"
