---
general_user: "vagrant-local"
general_password: "$6$gaagXYxRAIVVCA$rUek2lqIML2u5YBkFxMj.DOwC.ELGfI1K7iMyvlyH7bB4s9R/3MVmnEKoFV6hoWRSOH.78SAbrtlXd1rqBTXT0"
general_sshd_ports:
  - "22"

monit_port: "22122"
monit_credentials: "monit:monit"
monit_bind_address: "0.0.0.0"

keeweb_credentials: "vagrant:YYzo3ZBykz1oI"

netdata_credentials: "vagrant:YYzo3ZBykz1oI"
netdata_bind_address: "0.0.0.0"

dav_credentials: "dav:YYzo3ZBykz1oI"
dav_radicale_bind_address: "0.0.0.0"
dav_collections:
  - id: "personal"
    title: "Personal"
    color: "#063F33"
    type: "VCALENDAR"
  - id: "public"
    title: "Public"
    color: "#F33063"
    type: "VCALENDAR"
  - id: "contacts"
    title: "Contacts"
    type: "VADDRESSBOOK"
  - id: "work"
    title: "Work"
    type: "VADDRESSBOOK"
  - id: "astro"
    title: "Astro"
    color: "#0CA1FF"
    type: "VCALENDAR"
    url: "https://cantonbecker.com/astronomy-calendar/astrocal.ics"
    fileext: ".ics"
  - id: "premier_league"
    title: "Premier League"
    color: "#BE171B"
    type: "VCALENDAR"
    url: "https://ics.ecal.com/ecal-sub/5b7d89968cbe0763118b4569/Premier%20League.ics"
    fileext: ".ics"
    reminder: "TRIGGER\\:\\-P2DT"
    sed: ":a;N;\\$!ba;s#BEGIN:VALARM.*TRIGGER:-P2DT.*(BEGIN:VALARM)#\\1#g"

gallery_credentials: "vagrant:YYzo3ZBykz1oI"
gallery_sigal_pictures_source: "/home/vagrant/pictures"

sync_credentials: "vagrant:YYzo3ZBykz1oI"
sync_personal_credentials: "vagrant:YYzo3ZBykz1oI"
sync_personal_file: "vagrant.txt"

email_webmaster: "webmaster"

email_virtual_mailbox_users:
  - { email: "vagrant", real_email: "vagrant" }
  - { email: "vagrant-virtual", real_email: "vagrant" }
email_virtuals:
  - { email: "vagrant-virtual", real_email: "vagrant" }
email_virtual_regexs:
  - { regex: "/vagrant\\+.+/", real_email: "vagrant" }
email_credentials:
  - { email: "webmaster", pass: "xsoV/zOL9Ncz360Kz02xhLy+1aqXiw2bG+7qkcHbLq1+GOqsBAfXlS7OHtBuQroSXGHRu96IOPBgK/yqZmo1AB/NePc=" }
  - { email: "vagrant", pass: "lpiJyM6PEEZaoXHratE+NIUwTBErtWVqoZOhSJVa+O1Wl9ykwwIhkQ0CA6KpIFtWYsTkWh9EPLp6WgvpCtPw2Ilq7TQ=" }
email_mailboxes:
  - { name: "Starred", auto: "subscribe", special_use: "\\Flagged" }
  - { name: "Drafts", auto: "subscribe", special_use: "\\Drafts" }
  - { name: "Spam", auto: "subscribe", special_use: "\\Junk" }
  - { name: "Trash", auto: "subscribe", special_use: "\\Trash" }
  - { name: "Sent", auto: "subscribe", special_use: "\\Sent" }
  - { name: "Bills", auto: "subscribe" }
  - { name: "Travel/Tickets", auto: "subscribe" }
  - { name: "Sign Ups", auto: "subscribe" }
email_sieve_filters: |
  if header :contains "From" "work@{{ server }}" {
    fileinto :create "Work";
    keep;
  }

  if anyof (header :contains "To" "travels@{{ server }}",
            header :contains "From" "travels-express@{{ server }}") {
    fileinto :create "Travels";
    keep;
  }
