---
server: "vagrant.com"
general_user: "vagrant-server"
general_password: "$6$gaagXYxRAIVVCA$rUek2lqIML2u5YBkFxMj.DOwC.ELGfI1K7iMyvlyH7bB4s9R/3MVmnEKoFV6hoWRSOH.78SAbrtlXd1rqBTXT0"
general_sshd_ports:
  - "22"

nginx_user: "nginx"
nginx_folder: "/etc/nginx"
nginx_monit: "vagrant.local"
nginx_log: "/var/log/nginx"
nginx_content_folder: "/var/www"

letsencrypt_domains:
  - "vagrant.local"
  - "www.vagrant.local"
letsencrypt_email: "vagrant@local"
letsencrypt_folder: "/etc/letsencrypt"

monit_folder: "/etc/monit"
monit_port: "22122"
monit_username: "monit"
monit_password: "monit"
monit_alert_email: "vagrant@local"
monit_address: "monit.vagrant.local"

keeweb_address: "keeweb.vagrant.local"
keeweb_credentials: "vagrant:YYzo3ZBykz1oI"
