---
server: "localhost"

general_scripts_directory: "/usr/local/bin"
general_user: "vagrant-local"
general_password: "$6$gaagXYxRAIVVCA$rUek2lqIML2u5YBkFxMj.DOwC.ELGfI1K7iMyvlyH7bB4s9R/3MVmnEKoFV6hoWRSOH.78SAbrtlXd1rqBTXT0"
general_sshd_ports:
  - "22"

nginx_user: "nginx"
nginx_config_directory: "/etc/nginx"
nginx_log_directory: "/var/log/nginx"
nginx_content_directory: "/var/www"
nginx_pidfile: "/var/run/nginx.pid"

letsencrypt_config_directory: "/etc/letsencrypt"

monit_directory: "/etc/monit"
monit_port: "22122"
monit_credentials: "monit:monit"
monit_bind_address: "0.0.0.0"
monit_alert_email: "vagrant@local"
monit_logfile: "/var/log/monit.log"

keeweb_credentials: "vagrant:YYzo3ZBykz1oI"

netdata_credentials: "vagrant:YYzo3ZBykz1oI"
netdata_bind_address: "0.0.0.0"

dav_credentials: "dav:YYzo3ZBykz1oI"
dav_radicale_bind_address: "0.0.0.0"
dav_collections:
  - id: "personal"
    title: "Personal"
    color: "#063F33"
    type: "VCALENDAR"
  - id: "public"
    title: "Public"
    color: "#F33063"
    type: "VCALENDAR"
  - id: "contacts"
    title: "Contacts"
    type: "VADDRESSBOOK"
  - id: "work"
    title: "Work"
    type: "VADDRESSBOOK"
  - id: "astro"
    title: "Astro"
    color: "#0CA1FF"
    type: "VCALENDAR"
    url: "https://cantonbecker.com/astronomy-calendar/astrocal.ics"
    fileext: ".ics"
  - id: "premier_league"
    title: "Premier League"
    color: "#BE171B"
    type: "VCALENDAR"
    url: "https://ics.ecal.com/ecal-sub/5b7d89968cbe0763118b4569/Premier%20League.ics"
    fileext: ".ics"
    reminder: "TRIGGER\\:\\-P2DT"
    sed: ":a;N;\\$!ba;s#BEGIN:VALARM.*TRIGGER:-P2DT.*(BEGIN:VALARM)#\\1#g"

gallery_credentials: "vagrant:YYzo3ZBykz1oI"
gallery_sigal_pictures_source: "/home/vagrant/pictures"

sync_credentials: "vagrant:YYzo3ZBykz1oI"
sync_personal_credentials: "vagrant:YYzo3ZBykz1oI"
sync_personal_file: "vagrant.txt"

rkhunter_alert_email: "vagrant@local"

fail2ban_alert_email: "vagrant@local"
