---
server: "localhost"

general_user: "vagrant-local"
general_password: "$6$gaagXYxRAIVVCA$rUek2lqIML2u5YBkFxMj.DOwC.ELGfI1K7iMyvlyH7bB4s9R/3MVmnEKoFV6hoWRSOH.78SAbrtlXd1rqBTXT0"
general_sshd_ports:
  - "22"

nginx_user: "nginx"
nginx_config_directory: "/etc/nginx"
nginx_log_directory: "/var/log/nginx"
nginx_content_directory: "/var/www"

letsencrypt_config_directory: "/etc/letsencrypt"

monit_directory: "/etc/monit"
monit_port: "22122"
monit_credentials: "monit:monit"
monit_bind_address: "0.0.0.0"
monit_alert_email: "vagrant@local"
monit_logfile: "/var/log/monit.log"

keeweb_credentials: "vagrant:YYzo3ZBykz1oI"

netdata_credentials: "vagrant:YYzo3ZBykz1oI"
netdata_bind_address: "0.0.0.0"

dav_credentials: "vagrant:YYzo3ZBykz1oI"
dav_radicale_bind_address: "0.0.0.0"
dav_vdirsyncer_calendars:
  - { id: "premier_league", title: "Premier League", url: "https://ics.ecal.com/ecal-sub/5b7d89968cbe0763118b4569/Premier%20League.ics" }
  - { id: "astro", title: "Astro", url: "https://cantonbecker.com/astronomy-calendar/astrocal.ics" }
dav_vdisyncer_special_calendars:
  - { id: "premier_league", reminder: "TRIGGER\\:\\-P2DT", sed: ":a;N;\\$!ba;s#BEGIN:VALARM.*TRIGGER:-P2DT.*(BEGIN:VALARM)#\\1#g" }

gallery_credentials: "vagrant:YYzo3ZBykz1oI"
gallery_sigal_pictures_source: "/home/vagrant/pictures"

sync_credentials: "vagrant:YYzo3ZBykz1oI"
sync_personal_credentials: "vagrant:YYzo3ZBykz1oI"
sync_personal_file: "vagrant.txt"

rkhunter_alert_email: "vagrant@local"

fail2ban_alert_email: "vagrant@local"
