---
unbound_config_directory: "/etc/unbound"
unbound_roothints_url: "https://www.internic.net/domain/named.cache"

openresolv_config_directory: "/etc"
openresolv_local_name_servers:
  - "::1"
  - "127.0.0.1"
openresolv_name_servers:
  - "213.133.100.100"
  - "213.133.98.98"
  - "213.133.99.99"
  - "1.1.1.1"
  - "1.1.0.0"
