---
- name: "Check if nginx is installed"
  shell: "dpkg-query -W -f='${Status}' nginx | grep 'install ok installed'"
  failed_when: no
  changed_when: no
  register: nginx_check

- name: "Check if certificate already exists"
  stat:
    path: "{{ letsencrypt_config_directory }}/live/{{ server }}/cert.pem"
  register: letsencrypt_cert

- name: "Create {{ nginx_user }} user"
  user:
    name: "{{ nginx_user }}"
    shell: "/bin/false"
    createhome: no
    state: "present"
  when:
    - nginx_check.rc == 0
    - letsencrypt_cert is defined
    - letsencrypt_cert.stat.exists

- name: "Create Nginx directories for individual configurations"
  file:
    path: "{{ item }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "{{ nginx_config_directory }}/conf.d"
    - "{{ nginx_config_directory }}/conf"
  when:
    - nginx_check.rc == 0
    - letsencrypt_cert is defined
    - letsencrypt_cert.stat.exists

- name: "Copy default server settings"
  template:
    src: "nginx/{{ conf }}.j2"
    dest: "{{ nginx_config_directory }}/conf.d/{{ conf }}"
    mode: "0644"
  notify:
    - "Start Nginx"
    - "Reload Nginx"
  when:
    - nginx_check.rc == 0
    - letsencrypt_cert is defined
    - letsencrypt_cert.stat.exists

- name: "Create {{ nginx_config_directory }}/conf for credentials"
  file:
    path: "{{ nginx_config_directory }}/conf"
    mode: "0755"
    state: "directory"
  when:
    - nginx_check.rc == 0
    - letsencrypt_cert is defined
    - letsencrypt_cert.stat.exists

- name: "Copy credentials"
  template:
    src: "nginx/{{ credentials }}.j2"
    dest: "{{ nginx_config_directory }}/conf/{{ credentials }}"
    mode: "0644"
  notify:
    - "Start Nginx"
    - "Reload Nginx"
  when:
    - credentials is defined
    - nginx_check.rc == 0
    - letsencrypt_cert is defined
    - letsencrypt_cert.stat.exists
