---
- name: "Install nginx and ssl-cert"
  apt:
    name: "{{ item }}"
    default_release: "{{ ansible_distribution_release }}-backports"
    state: "latest"
  with_items:
    - "nginx"
    - "ssl-cert"

- name: "Create {{ nginx_user }} user"
  user:
    name: "{{ nginx_user }}"
    shell: "/bin/false"
    createhome: no
    state: "present"

- name: "Create {{ nginx_content_directory }} directory"
  file:
    path: "{{ nginx_content_directory }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"
    state: "directory"

- name: "Ensure {{ nginx_log_directory }} permissions are set"
  file:
    path: "{{ nginx_log_directory }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"
    state: "directory"

- name: "Check if DHE parameter exists"
  stat:
    path: "{{ nginx_ssl_dhparam }}"
  register: dhe_parameter

- name: "Generate a stronger DHE parameter"
  command: "openssl dhparam -out {{ nginx_ssl_dhparam }} 4096"
  when: dhe_parameter is defined and dhe_parameter.stat.islnk is not defined

- name: "Copy main settings"
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_config_directory }}/nginx.conf"
    mode: "0644"
  notify: "Reload Nginx"

- name: "Create Nginx directories for individual configurations"
  file:
    path: "{{ item }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "{{ nginx_config_directory }}/conf.d"
    - "{{ nginx_config_directory }}/conf"

- name: "Copy default server settings"
  template:
    src: "conf.d/default.conf.j2"
    dest: "{{ nginx_config_directory }}/conf.d/default.conf"
    mode: "0644"
  notify: "Reload Nginx"

- name: "Check for letsencrypt configuration"
  stat:
    path: "{{ nginx_config_directory }}/conf.d/letsencrypt.conf"
  register: st_letsencrypt

- name: "Add placeholder certificates"
  lineinfile:
    path: "{{ nginx_config_directory }}/conf.d/default.conf"
    regexp: '{{ item }}'
    line: "  {{ item }};"
    insertafter: "server_name"
  with_items:
    - "ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key"
    - "ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem"
  notify: "Reload Nginx"
  when: st_letsencrypt is defined and not st_letsencrypt.stat.exists

- name: "Enable/start nginx"
  systemd:
    name: "nginx"
    state: "started"
    enabled: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "nginx"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "nginx"
