---
- name: "Update nginx keys"
  apt_key:
    url: "{{ nginx_key_url }}"
    state: "present"
  become: yes

- name: "Update nginx apt sources"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
  with_items:
    - "deb {{ nginx_deb_package }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
    - "deb-src {{ nginx_deb_package }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx"
  become: yes

- name: "Install nginx and ssl-cert"
  apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: yes
  with_items:
    - "nginx"
    - "ssl-cert"
  become: yes

- name: "Create {{ nginx_user }} user"
  user:
    name: "{{ nginx_user }}"
    shell: "/bin/false"
    createhome: no
    state: "present"
  become: yes

- name: "Create {{ nginx_content_folder }} folder"
  file:
    path: "{{ nginx_content_folder }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0600"
    state: "directory"
  become: yes

- name: "Ensure {{ nginx_log }} permissions are set"
  file:
    path: "{{ nginx_log }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"
    state: "directory"
  become: yes

- name: "Copy main settings"
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_folder }}/nginx.conf"
    mode: "0644"
  notify:
    - "Start Nginx"
    - "Reload Nginx"
  become: yes

- name: "Copy default server settings"
  template:
    src: "conf.d/default.conf.j2"
    dest: "{{ nginx_folder }}/conf.d/default.conf"
    mode: "0644"
  notify:
    - "Start Nginx"
    - "Reload Nginx"
  become: yes

- name: "Check for letsencrypt configuration"
  stat:
    path: "{{ nginx_folder }}/conf.d/letsencrypt.conf"
  register: st_letsencrypt

- name: "Add placeholder certificates"
  lineinfile:
    path: "{{ nginx_folder }}/conf.d/default.conf"
    regexp: '{{ item }}'
    line: "  {{ item }};"
    insertafter: "server_name"
  with_items:
    - "ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key"
    - "ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem"
  notify:
    - "Start Nginx"
    - "Reload Nginx"
  become: yes
  when: st_letsencrypt is defined and not st_letsencrypt.stat.exists

- name: "Enable/start nginx"
  systemd:
    name: "nginx"
    state: "started"
    enabled: yes
  become: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "nginx"
