---
- name: "install Rkhunter"
  apt:
    name: "rkhunter"
    state: "latest"

- name: "create Rkhunter directories"
  file:
    path: "{{ item }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "{{ rkhunter_config_directory }}"
    - "{{ rkhunter_default_directory }}"

- name: "copy Rkhunter settings"
  template:
    src: "{{ item.filename }}.j2"
    dest: "{{ item.directory }}/{{ item.filename }}"
    mode: "0644"
  with_items:
    - { directory: "{{ rkhunter_config_directory }}", filename: "rkhunter.conf" }
    - { directory: "{{ rkhunter_default_directory }}", filename: "rkhunter" }

- name: "update Rkhunter"
  command: "rkhunter --update"
  register: rkhunter_update
  failed_when:
    - rkhunter_update.failed
    - not "Updated" in rkhunter_update.stdout

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "rkhunter"
