---
- name: "Reload Nginx"
  systemd:
    name: "nginx"
    state: "reloaded"

- name: "Restart Nginx"
  systemd:
    name: "nginx"
    state: "restarted"

- name: "Restart incron"
  systemd:
    name: "incron"
    state: "restarted"

- name: "Reload systemd"
  systemd:
    daemon_reload: yes
