---
- name: "Check if monit is installed"
  shell: "dpkg-query -W -f='${Status}' monit | grep 'install ok installed'"
  failed_when: no
  changed_when: no
  register: monit_check

- name: "Create Monit directories"
  block:
    - file: path="{{ monit_directory }}/conf-available" mode="0755" state="directory"
    - file: path="{{ monit_directory }}/conf-enabled" mode="0755" state="directory"
  become: yes
  when: monit_check.rc == 0

- name: "Copy {{ conf }} configuration"
  template:
    src: "monit/{{ conf }}.j2"
    dest: "{{ monit_directory }}/conf-available/{{ conf }}"
    mode: "0644"
  notify:
    - "Start Monit"
    - "Reload Monit"
  become: yes
  when: monit_check.rc == 0

- name: "Symlink {{ conf }} configuration"
  file:
    src: "{{ monit_directory }}/conf-available/{{ conf }}"
    dest: "{{ monit_directory }}/conf-enabled/{{ conf }}"
    state: "link"
  notify:
    - "Start Monit"
    - "Reload Monit"
  become: yes
  when: monit_check.rc == 0
