---
- name: "Install monit"
  apt:
    name: "monit"
    state: "latest"
    update_cache: yes
  become: yes

- name: "Copy Monit settings"
  template:
    src: "monitrc.j2"
    dest: "{{ monit_directory }}/monitrc"
    mode: "0600"
  notify:
    - "Start Monit"
    - "Reload Monit"
  become: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  with_items:
    - "monit"
    - "system"
  loop_control:
    loop_var: "conf"

- name: "Start/enable monit"
  systemd:
    name: "monit"
    state: "started"
    enabled: yes
  become: yes

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "monit.conf"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "monit"
