---
- name: "Install monit"
  apt:
    name: "monit"
    state: "latest"

- name: "Copy Monit settings"
  template:
    src: "monitrc.j2"
    dest: "{{ monit_config_directory }}/monitrc"
    mode: "0600"
  notify: "Reload Monit"

- include_role:
    name: "monit"
    tasks_from: "configure"
  with_items:
    - "monit"
    - "system"
  loop_control:
    loop_var: "conf"

- name: "Start/enable monit"
  systemd:
    name: "monit"
    state: "started"
    enabled: yes

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "monit.conf"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "monit"
