---
- name: "Update backports apt sources"
  apt_repository:
    repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: "present"
  become: yes

- name: "Install Netdata"
  apt:
    name: "netdata"
    state: "latest"
    update_cache: yes
  become: yes

- name: "Copy Netdata settings"
  template:
    src: "netdata.conf.j2"
    dest: "{{ netdata_config_directory }}/netdata.conf"
    mode: "0600"
  notify: "Restart Netdata"
  become: yes

- name: "Start/enable Netdata"
  systemd:
    name: "netdata"
    state: "started"
    enabled: yes
  become: yes

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "netdata.conf"
    credentials: "htpasswd.netdata"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "netdata"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "netdata"
