---
- name: "Install Netdata and utilities"
  apt:
    name:
      - "netdata"
      - "iw"
      - "fping"
      - "python-dnspython"
    state: "latest"

- name: "Add required groups to Netdata"
  user:
    name: "netdata"
    groups:
      - "nginx"
      - "adm"
      - "proxy"

- name: "Copy Netdata settings"
  template:
    src: "{{ item }}.j2"
    dest: "{{ netdata_config_directory }}/{{ item }}"
    mode: "0644"
  with_items:
    - "netdata.conf"
    - "python.d.conf"
  notify: "Restart Netdata"

- name: "Create Netdata Python directory"
  file:
    path: "{{ netdata_config_directory }}/python.d"
    mode: "0755"
    state: "directory"

- name: "Copy Netdata Python settings"
  template:
    src: "python.d/{{ item }}.conf.j2"
    dest: "{{ netdata_config_directory }}/python.d/{{ item }}.conf"
    mode: "0644"
  with_items:
    - "postfix"
    - "web_log"
    - "dovecot"
    - "nginx"
  notify: "Restart Netdata"

- name: "Set correct recipient for email"
  lineinfile:
    path: "{{ netdata_config_directory }}/health_alarm_notify.conf"
    regexp: 'DEFAULT_RECIPIENT_EMAIL='
    line: 'DEFAULT_RECIPIENT_EMAIL={{ email_webmaster }}@{{ server }}'
  notify: "Restart Netdata"

- name: "Start/enable Netdata"
  systemd:
    name: "netdata"
    state: "started"
    enabled: yes

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "netdata.conf"
    credentials:
      - "htpasswd.netdata"

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "localhost.conf"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "netdata"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "netdata"
