---
- name: "Install utilities for netdata"
  apt:
    name:
      - "acl"
      - "iw"
      - "fping"
      - "python-dnspython"
    state: "latest"

- name: "Check if netdata is installed"
  stat:
    path: "/usr/sbin/netdata"
  register: netdata

- name: "Install netdata"
  block:
    - tempfile: suffix="netdata" state="directory"
      register: tempdir
    - get_url: url="{{ netdata_url }}" dest="{{ tempdir.path }}/installer.sh" checksum="{{ netdata_checksum }}"
    - command: "bash {{ tempdir.path }}/installer.sh --non-interactive --no-updates --stable-channel --disable-telemetry"
  always:
    - file: path="{{ tempdir.path }}" state="absent"
  when: (netdata is defined and netdata.stat.islnk is not defined) or (update is defined and update)

- name: "Copy Netdata settings"
  template:
    src: "{{ item }}.j2"
    dest: "{{ netdata_config_directory }}/{{ item }}"
    mode: "0644"
  with_items:
    - "netdata.conf"
    - "health_alarm_notify.conf"
  notify: "Restart Netdata"

- name: "Copy Netdata Python settings"
  template:
    src: "python.d/{{ item }}.conf.j2"
    dest: "{{ netdata_config_directory }}/python.d/{{ item }}.conf"
    mode: "0644"
  with_items:
    - "monit"
    - "postgres"
    - "web_log"
  notify: "Restart Netdata"

- name: "Copy Netdata Go settings"
  template:
    src: "go.d/{{ item }}.conf.j2"
    dest: "{{ netdata_config_directory }}/go.d/{{ item }}.conf"
    mode: "0644"
  with_items:
    - "unbound"
  notify: "Restart Netdata"

- name: "Define permissions for Netdata to access Unbound"
  acl:
    path: "{{ unbound_config_directory }}/{{ item }}"
    entity: "netdata"
    etype: "user"
    permissions: "r"
    state: "present"
  with_items:
    - "unbound.conf"
    - "unbound_control.key"
    - "unbound_control.pem"

- name: "Define permissions for Netdata to access Dovecot stats"
  acl:
    path: "/var/run/dovecot/old-stats"
    entity: "netdata"
    etype: "user"
    permissions: "rw"
    state: "present"

- name: "Start/enable Netdata"
  systemd:
    name: "netdata"
    state: "started"
    enabled: yes

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "netdata.conf"
    credentials:
      - "htpasswd.netdata"

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "localhost.conf"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "netdata"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "netdata"
