---
- name: "Restart ledger timer"
  systemd:
    name: "ledger.timer"
    state: "restarted"
    daemon_reload: yes

- name: "Restart ledger-backup timer"
  systemd:
    name: "ledger-backup.timer"
    state: "restarted"
    daemon_reload: yes

- name: "Restart ledger-networth timer"
  systemd:
    name: "ledger-networth.timer"
    state: "restarted"
    daemon_reload: yes

- name: "Restart PostgreSQL"
  systemd:
    name: "postgresql"
    state: "restarted"

- name: "Restart PHP-FPM"
  systemd:
    name: "php{{ ledger_firefly_php_version }}-fpm"
    state: "restarted"
