---
- name: "create {{ dav_user }} user"
  user:
    name: "{{ dav_user }}"
    shell: "/bin/false"
    home: "{{ dav_radicale_collections_directory }}"
    state: "present"

- import_tasks: "radicale.yml"
- import_tasks: "vdirsyncer.yml"
