---
- name: "Install radicale"
  apt:
    name: "radicale"
    state: "latest"

- name: "Create Radicale directories"
  file:
    path: "{{ item.path }}"
    owner: "{{ dav_user }}"
    group: "{{ dav_user }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items:
    - { path: "{{ dav_radicale_config_directory }}", mode: "0744" }
    - { path: "{{ dav_radicale_log_directory }}", mode: "0755" }

- name: "Copy Radicale settings"
  template:
    src: "radicale/{{ item }}.j2"
    dest: "{{ dav_radicale_config_directory }}/{{ item }}"
    owner: "{{ dav_user }}"
    group: "{{ dav_user }}"
    mode: "0644"
  with_items:
    - "config"
    - "logging"
  notify: "Restart Radicale"

- name: "Prepare property files for collections"
  block:
    - file:
        path: "{{ dav_home }}/collection-root/{{ dav_radicale_collection }}/{{ item.id }}"
        owner: "{{ dav_user }}"
        group: "{{ dav_user }}"
        mode: "0750"
        state: "directory"
      with_items: "{{ dav_collections }}"
    - template:
        src: "radicale/radicale.props.j2"
        dest: "{{ dav_home }}/collection-root/{{ dav_radicale_collection }}/{{ item.id }}/.Radicale.props"
        owner: "{{ dav_user }}"
        group: "{{ dav_user }}"
        mode: "0600"
        force: no
      with_items: "{{ dav_collections }}"
  no_log: yes

- name: "Create Radicale service directory"
  file:
    path: "{{ systemd_directory }}/radicale.service.d"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

- name: "Override Radicale service"
  template:
    src: "radicale/override.conf.j2"
    dest: "{{ systemd_directory }}/radicale.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart Radicale"

- name: "Enable Radicale"
  systemd:
    name: "radicale"
    state: "started"
    enabled: yes
    daemon_reload: yes

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "dav.conf"
    credentials:
      - "htpasswd.dav"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "dav"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "dav"
