---
- name: "Install python3 and pip3"
  apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: yes
  with_items:
    - "python3"
    - "python3-pip"
  become: yes

- name: "Ensure group {{ dav_group }} exists"
  group:
    name: "{{ dav_group }}"
    state: "present"
  become: yes

- name: "Create {{ dav_radicale_user }} user"
  user:
    name: "{{ dav_radicale_user }}"
    group: "{{ dav_group }}"
    shell: "/bin/false"
    state: "present"
    create_home: no
  become: yes

- name: "Install Radicale"
  pip:
    name: "radicale"
    state: "latest"
    executable: "pip3"
  notify:
    - "Start Radicale"
    - "Reload Radicale"
  become: yes

- name: "Create Radicale folders"
  file:
    path: "{{ item.path }}"
    owner: "{{ dav_radicale_user }}"
    group: "{{ dav_group }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items:
    - { path: "{{ dav_radicale_config }}", mode: "0744" }
    - { path: "{{ dav_radicale_pid }}", mode: "0744" }
    - { path: "{{ dav_radicale_log }}", mode: "0755" }
    - { path: "{{ dav_radicale_collections }}", mode: "0775" }
  become: yes

- name: "Copy Radicale settings"
  template:
    src: "radicale/{{ item }}.j2"
    dest: "{{ dav_radicale_config }}/{{ item }}"
    owner: "{{ dav_radicale_user }}"
    group: "{{ dav_group }}"
    mode: "0644"
  with_items:
    - "config"
    - "logging"
  notify:
    - "Start Radicale"
    - "Reload Radicale"
  become: yes

- name: "Copy Radicale systemd"
  template:
    src: "radicale/radicale.service.j2"
    dest: "/etc/systemd/system/radicale.service"
    mode: "0744"
  notify:
    - "Reload daemon"
    - "Start Radicale"
    - "Reload Radicale"
  become: yes

- name: "Stat/Enable Radicale"
  systemd:
    name: "radicale"
    state: "started"
    enabled: yes
    daemon_reload: yes
  become: yes

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "dav.conf"
    credentials: "htpasswd.dav"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "dav"
