---
- name: "Install python3 and pip3"
  apt:
    name: "{{ item }}"
    state: "latest"
    update_cache: yes
  with_items:
    - "python3"
    - "python3-pip"

- name: "Create {{ dav_user }} user"
  user:
    name: "{{ dav_user }}"
    group: "{{ dav_user }}"
    shell: "/bin/false"
    state: "present"
    create_home: no

- name: "Install Radicale"
  pip:
    name: "radicale"
    state: "latest"
    executable: "pip3"
  notify: "Restart Radicale"

- name: "Create Radicale directories"
  file:
    path: "{{ item.path }}"
    owner: "{{ dav_user }}"
    group: "{{ dav_user }}"
    mode: "{{ item.mode }}"
    state: "directory"
  with_items:
    - { path: "{{ dav_radicale_config_directory }}", mode: "0744" }
    - { path: "{{ dav_radicale_pid_directory }}", mode: "0744" }
    - { path: "{{ dav_radicale_log_directory }}", mode: "0755" }
    - { path: "{{ dav_radicale_collections_directory }}", mode: "0775" }

- name: "Copy Radicale settings"
  template:
    src: "radicale/{{ item }}.j2"
    dest: "{{ dav_radicale_config_directory }}/{{ item }}"
    owner: "{{ dav_user }}"
    group: "{{ dav_user }}"
    mode: "0644"
  with_items:
    - "config"
    - "logging"
  notify: "Restart Radicale"

- name: "Copy Radicale systemd"
  template:
    src: "radicale/radicale.service.j2"
    dest: "/etc/systemd/system/radicale.service"
    mode: "0644"
  notify:
    - "Reload daemon"
    - "Restart Radicale"

- name: "Start/Enable Radicale"
  systemd:
    name: "radicale"
    state: "started"
    enabled: yes
    daemon_reload: yes

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "dav.conf"
    credentials: "htpasswd.dav"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "dav"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "dav"
