---
- name: "Ensure group {{ dav_group }} exists"
  group:
    name: "{{ dav_group }}"
    state: "present"

- name: "Create {{ dav_vdirsyncer_user }} user"
  user:
    name: "{{ dav_vdirsyncer_user }}"
    group: "{{ dav_group }}"
    shell: "/bin/false"
    state: "present"
    create_home: no

- name: "Install Vdirsyncer"
  apt:
    name: "vdirsyncer"
    state: "latest"
    update_cache: yes

- name: "Create Vdirsyncer directories"
  file:
    path: "{{ dav_vdirsyncer_config_directory }}"
    owner: "{{ dav_vdirsyncer_user }}"
    group: "{{ dav_group }}"
    mode: "0755"
    state: "directory"

- name: "Copy Vdirsyncer settings"
  template:
    src: "vdirsyncer/config.j2"
    dest: "{{ dav_vdirsyncer_config_directory }}/config"
    owner: "{{ dav_vdirsyncer_user }}"
    group: "{{ dav_group }}"
    mode: "0600"
  notify: "Restart Vdirsyncer timer"

- name: "Copy Vdirsyncer script"
  template:
    src: "vdirsyncer/{{ item }}.j2"
    dest: "{{ dav_vdirsyncer_config_directory }}/{{ item }}"
    owner: "{{ dav_vdirsyncer_user }}"
    group: "{{ dav_group }}"
    mode: "0700"
  with_items:
    - "vsync"
    - "vdiscover"

- name: "Copy Vdirsyncer systemd"
  template:
    src: "vdirsyncer/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0755"
  with_items:
    - "vdirsyncer.service"
    - "vdirsyncer.timer"
  notify:
    - "Reload daemon"
    - "Restart Vdirsyncer timer"

- name: "Discover collections"
  shell: "yes | {{ dav_vdirsyncer_config_directory }}/vdiscover"
  notify:
    - "Reload daemon"
    - "Restart Vdirsyncer timer"

- name: "Run Vdirsyncer oneshot service"
  systemd:
    name: "vdirsyncer"
    state: "started"

- name: "Start/Enable Vdirsyncer"
  systemd:
    name: "vdirsyncer.timer"
    state: "started"
    enabled: yes
    daemon_reload: yes
