---
- name: "create {{ dav_user }} user"
  user:
    name: "{{ dav_user }}"
    shell: "/bin/false"
    state: "present"
    create_home: no

- name: "install Vdirsyncer"
  apt:
    name: "vdirsyncer"
    state: "latest"

- name: "create Vdirsyncer directories"
  file:
    path: "{{ dav_vdirsyncer_config_directory }}"
    owner: "{{ dav_user }}"
    mode: "0755"
    state: "directory"

- name: "copy Vdirsyncer settings"
  template:
    src: "vdirsyncer/config.j2"
    dest: "{{ dav_vdirsyncer_config_directory }}/config"
    owner: "{{ dav_user }}"
    group: "{{ dav_user }}"
    mode: "0600"
  register: vdirsyncer_settings

- include_role:
    name: "general"
    tasks_from: "scripts"
  with_items:
    - "vsync"
    - "vdiscover"
  loop_control:
    loop_var: "script"

- name: "copy Vdirsyncer systemd"
  template:
    src: "vdirsyncer/{{ item }}.j2"
    dest: "{{ systemd_directory }}/{{ item }}"
    mode: "0755"
  with_items:
    - "vdirsyncer.service"
    - "vdirsyncer.timer"
  notify: "restart Vdirsyncer"

- name: "discover collections"
  shell: "yes | vdiscover"
  environment:
    LC_ALL: "{{ dav_vdirsyncer_locale }}"
    LANG: "{{ dav_vdirsyncer_locale }}"
  when: vdirsyncer_settings is defined and vdirsyncer_settings.changed

- name: "run Vdirsyncer oneshot service"
  systemd:
    name: "vdirsyncer"
    state: "started"
  when: vdirsyncer_settings is defined and vdirsyncer_settings.changed

- name: "start/Enable Vdirsyncer"
  systemd:
    name: "vdirsyncer.timer"
    state: "started"
    enabled: yes
    daemon_reload: yes
