---
- name: "Install Logrotate"
  apt:
    name: "logrotate"
    state: "latest"
    update_cache: yes

- name: "Copy Logrotate settings"
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    mode: "0644"

- name: "Create Logrotate directory"
  file:
    path: "{{ logrotate_config_directory }}"
    mode: "0755"
    state: "directory"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  with_items:
    - "apt"
    - "dpkg"
  loop_control:
    loop_var: "conf"
