---
- name: "Reload SSH"
  systemd:
    name: "ssh"
    state: "reloaded"

- name: "Restart server configuration"
  command: "systemctl daemon-reexec"

- name: "Restart Rsyslog"
  systemd:
    name: "rsyslog"
    state: "restarted"
    daemon_reload: yes

- name: "Reload systemd"
  systemd:
    daemon_reload: yes
