---
- name: "Reload SSH"
  systemd:
    name: "ssh"
    state: "reloaded"

- name: "Restart server configuration"
  command: "systemctl daemon-reexec"

- name: "Reload systemd"
  systemd:
    daemon_reload: yes
