---
- name: "Install Logwatch"
  apt:
    name: "logwatch"
    state: "latest"

- name: "Create Logwatch custom configuration directory"
  file:
    path: "{{ logwatch_directory }}"
    state: directory

- name: "Configure Logwatch"
  template:
    src: "logwatch/{{ item }}.j2"
    dest: "{{ logwatch_directory }}/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "logwatch.conf"
    - "systemd.conf"

- name: "Copy service and timer for logwatch"
  template:
    src: "systemd/{{ item }}.j2"
    dest: "{{ systemd_directory }}/{{ item }}"
    mode: "0600"
  with_items:
    - "logwatch.service"
    - "logwatch.timer"
  notify:
    - "Restart logwatch timer"

- name: "Start/Enable Logwatch timer"
  systemd:
    name: "logwatch.timer"
    state: "started"
    enabled: yes
    daemon_reload: yes
