---
- name: "Create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    shell: "/bin/bash"
    state: "present"

- name: "Set authorized key from local user"
  authorized_key:
    user: "{{ general_user }}"
    key: "{{ lookup('file', '~/.ssh/server_id_rsa.pub') }}"
    state: "present"

- name: "Add {{ general_user }} to sudoers"
  lineinfile:
    path: "/etc/sudoers"
    regexp: '{{ general_user }} ALL=\(ALL\) ALL'
    line: "{{ general_user }} ALL=(ALL) ALL"
    validate: "visudo -cf %s"
    backup: yes

- name: "Set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "Reload SSH"

- name: "Set systemd settings"
  template:
    src: "system.conf.j2"
    dest: "/etc/systemd/system.conf"
    mode: "0644"
  notify: "Restart server configuration"

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "pserver-stats"

- name: "Create Rsyslog service directory"
  file:
    path: "{{ systemd_directory }}/rsyslog.service.d"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

- name: "Override Rsyslog exec command"
  template:
    src: "systemd/rsyslog.conf.j2"
    dest: "{{ systemd_directory }}/rsyslog.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart Rsyslog"

- include_role:
    name: "monit"
    tasks_from: "configure"
  with_items:
    - "acpid"
    - "at"
    - "cron"
    - "openssh-server"
    - "rsyslog"
  loop_control:
    loop_var: "conf"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "rsyslog"

- name: "Install vim, curl and some other utilities"
  apt:
    name:
      - "vim"
      - "curl"
      - "at"
      - "acpid"
      - "rsyslog"
      - "tmux"
    state: "latest"
