---
- name: "update backports apt sources"
  apt_repository:
    repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
    state: "present"
  become: yes

- name: "Update current packages"
  apt:
    upgrade: yes
    update_cache: yes
    force_apt_get: yes
  become: yes

- name: "Install vim, curl and some other utilities"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "vim"
    - "curl"
    - "at"
    - "acpid"
    - "rsyslog"
  become: yes

- name: "Create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    shell: "/bin/bash"
    state: "present"
  become: yes

- name: "Set authorized key from local user"
  authorized_key:
    user: "{{ general_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: "present"
  become: yes

- name: "Add {{ general_user }} to sudoers"
  lineinfile:
    path: "/etc/sudoers"
    regexp: '{{ general_user }} ALL=\(ALL\) ALL'
    line: "{{ general_user }} ALL=(ALL) ALL"
    validate: "visudo -cf %s"
    backup: yes
  become: yes

- name: "Set sshd settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "reload ssh"
  become: yes

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "pserver-stats"

- include_role:
    name: "monit"
    tasks_from: "configure"
  with_items:
    - "acpid"
    - "at"
    - "cron"
    - "openssh-server"
    - "rsyslog"
  loop_control:
    loop_var: "conf"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "rsyslog"
