---
- name: "create {{ general_user }} user"
  user:
    name: "{{ general_user }}"
    password: "{{ general_password }}"
    create_home: yes
    shell: "/bin/bash"
    state: "present"

- name: "set authorized key from local user"
  authorized_key:
    user: "{{ general_user }}"
    key: "{{ lookup('file', '~/.ssh/server_id_rsa.pub') }}"
    state: "present"

- name: "add {{ general_user }} to sudoers"
  lineinfile:
    path: "/etc/sudoers"
    regexp: '{{ general_user }} ALL=\(ALL\) ALL'
    line: "{{ general_user }} ALL=(ALL) ALL"
    validate: "visudo -cf %s"
    backup: yes

- name: "set SSHD settings"
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "0644"
  notify: "reload SSH"

- name: "set systemd settings"
  template:
    src: "system.conf.j2"
    dest: "/etc/systemd/system.conf"
    mode: "0644"
  notify: "restart server configuration"

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "pserver-stats"

- include_role:
    name: "monit"
    tasks_from: "configure"
  with_items:
    - "acpid"
    - "at"
    - "cron"
    - "openssh-server"
    - "rsyslog"
  loop_control:
    loop_var: "conf"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "rsyslog"

- import_tasks: "utilities.yml"
