---
- name: "create directory for scripts"
  file:
    path: "{{ general_scripts_directory }}"
    mode: "02775"
    state: "directory"

- name: "copy server custom scripts"
  template:
    src: "scripts/{{ script }}.j2"
    dest: "{{ general_scripts_directory }}/{{ script }}"
    mode: "0755"
