---
- name: "install vim, curl and some other utilities"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "vim"
    - "curl"
    - "at"
    - "acpid"
    - "rsyslog"
    - "htop"

- name: "copy htop configuration file"
  template:
    src: "htoprc.j2"
    dest: "/etc/htoprc"
    mode: "0644"
