---
- name: "install vim, curl and some other utilities"
  apt:
    name:
      - "vim"
      - "curl"
      - "at"
      - "acpid"
      - "rsyslog"
      - "htop"
    state: "latest"

- name: "copy htop configuration file"
  template:
    src: "htoprc.j2"
    dest: "/etc/htoprc"
    mode: "0644"
