---
- name: "reload OpenDKIM"
  systemd:
    name: "opendkim"
    state: "reloaded"

- name: "reload SpamAssassin"
  systemd:
    name: "spamassassin"
    state: "reloaded"

- name: "restart spamass-milter"
  systemd:
    name: "spamass-milter"
    state: "restarted"

- name: "restart sa-learn"
  systemd:
    name: "sa-learn.timer"
    state: "restarted"

- name: "reload Postfix"
  systemd:
    name: "postfix"
    state: "reloaded"

- name: "reload Dovecot"
  systemd:
    name: "dovecot"
    state: "reloaded"

- name: "restart Pflogsumm"
  systemd:
    name: "pflogsumm.timer"
    state: "restarted"
