---
- name: "Reload OpenDKIM"
  systemd:
    name: "opendkim"
    state: "reloaded"

- name: "Display message about OpenDKIM keys"
  debug:
    msg:
      - "Please run"
      - "ssh -p {{ general_sshd_ports[0] }} -t {{ general_user }}@{{ ansible_default_ipv4.address }} 'cat {{ email_opendkim_config_directory }}/mail.txt'"
      - "and add the result to the register"

- name: "Reload SpamAssassin"
  systemd:
    name: "spamassassin"
    state: "reloaded"

- name: "Restart spamass-milter"
  systemd:
    name: "spamass-milter"
    state: "restarted"

- name: "Restart sa-learn"
  systemd:
    name: "sa-learn.timer"
    state: "restarted"

- name: "Reload Postfix"
  systemd:
    name: "postfix"
    state: "reloaded"

- name: "Reload Dovecot"
  systemd:
    name: "dovecot"
    state: "reloaded"

- name: "Restart Pflogsumm"
  systemd:
    name: "pflogsumm.timer"
    state: "restarted"

- name: "Reload Nginx"
  systemd:
    name: "nginx"
    state: "reloaded"
