---
- name: "Start Postfix"
  systemd:
    name: "postfix"
    state: "started"

- name: "Reload Postfix"
  systemd:
    name: "postfix"
    state: "reloaded"

- name: "Start Dovecot"
  systemd:
    name: "dovecot"
    state: "started"

- name: "Reload Dovecot"
  systemd:
    name: "dovecot"
    state: "reloaded"

- name: "Start OpenDKIM"
  systemd:
    name: "opendkim"
    state: "started"

- name: "Reload OpenDKIM"
  systemd:
    name: "opendkim"
    state: "reloaded"

- name: "Start SpamAssassin"
  systemd:
    name: "{{ item }}"
    state: "started"
  with_items:
    - "spamassassin"
    - "spamass-milter"

- name: "Reload SpamAssassin"
  systemd:
    name: "{{ item }}"
    state: "reloaded"
  with_items:
    - "spamassassin"
    - "spamass-milter"
