---
- name: "Start Postfix"
  systemd:
    name: "postfix"
    state: "started"
  register: postfix_service_start
  failed_when:
    - postfix_service_start.failed
    - not "Could not find the requested service" in postfix_service_start.msg

- name: "Reload Postfix"
  systemd:
    name: "postfix"
    state: "reloaded"
  register: postfix_service_reload
  failed_when:
    - postfix_service_reload.failed
    - not "Could not find the requested service" in postfix_service_reload.msg
