---
- name: "Update apt sources to include new version of PHP"
  block:
    - apt_key: id="{{ apt_sury_key }}" url="{{ apt_sury_repo }}/apt.gpg" state="present"
    - apt_repository: repo="deb {{ apt_sury_repo }} {{ ansible_distribution_release }} main" state="present"
    - apt: update_cache=yes

- name: "Install PHP"
  apt:
    name:
      - "php{{ ledger_firefly_php_version }}"
      - "php{{ ledger_firefly_php_version }}-bcmath"
      - "php{{ ledger_firefly_php_version }}-intl"
      - "php{{ ledger_firefly_php_version }}-curl"
      - "php{{ ledger_firefly_php_version }}-zip"
      - "php{{ ledger_firefly_php_version }}-gd"
      - "php{{ ledger_firefly_php_version }}-xml"
      - "php{{ ledger_firefly_php_version }}-mbstring"
      - "php{{ ledger_firefly_php_version }}-ldap"
      - "php{{ ledger_firefly_php_version }}-pgsql"
      - "php{{ ledger_firefly_php_version }}-fpm"
      - "composer"
    state: "latest"

- name: "Add configuration for PHP-FPM"
  template:
    src: "php/{{ item.name }}.j2"
    dest: "{{ ledger_firefly_phpfpm_config_directory }}/{{ item.directory }}{{ item.name }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - { name: "php.ini", directory: "" }
    - { name: "www.conf", directory: "pool.d/" }
  notify: "Restart PHP-FPM"

- name: "Start/Enable PHP-FPM"
  service:
    name: "php{{ ledger_firefly_php_version }}-fpm"
    state: "started"
    enabled: yes

- name: "Check if Firefly III has been installed"
  stat:
    path: "{{ ledger_firefly_directory }}"
  register: firefly_iii_installed

- name: "Download and install Firefly III"
  block:
    - tempfile: suffix="firefly" state="directory"
      register: tempdir
    - get_url: url="{{ ledger_firefly_url }}" dest="{{ tempdir.path }}" checksum="sha256:{{ ledger_firefly_url }}.sha256"
    - file: path="{{ webserver_nginx_content_directory }}/{{ ledger_firefly_name }}" mode="0755" state="directory"
    - unarchive: src="{{ ledger_firefly_url }}" dest="{{ webserver_nginx_content_directory }}/{{ ledger_firefly_name }}" remote_src=yes
    - file: path="{{ webserver_nginx_content_directory }}/{{ ledger_firefly_name }}" owner="{{ webserver_nginx_user }}" group="{{ webserver_nginx_user }}" mode="0755" state="directory" recurse=yes
  always:
    - file: path="{{ tempdir.path }}" state="absent"
  when:
    - firefly_iii_installed is defined
    - firefly_iii_installed.stat.islnk is not defined

- name: "Add configuration for Firefly III"
  template:
    src: "firefly/env.j2"
    dest: "{{ ledger_firefly_directory }}/.env"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    mode: "0644"

- name: "Final steps for installation"
  command: "sudo -E -u {{ webserver_nginx_user }} php artisan {{ item }}"
  args:
    chdir: "{{ ledger_firefly_directory }}"
  with_items:
    - "firefly-iii:upgrade-database"
    - "firefly-iii:correct-database"
    - "firefly-iii:report-integrity"
    - "firefly-iii:laravel-passport-keys"
  when:
    - firefly_iii_installed is defined
    - firefly_iii_installed.stat.islnk is not defined

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "ledger.conf"
    credentials:
      - "htpasswd.ledger"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "ledger"
