---
- name: "Update apt sources to include new version of PHP"
  block:
    - apt_key: key="{{ apt_sury_key }}" url="{{ apt_sury_repo }}/apt.gpg" state="present"
    - apt_repository: repo="deb {{ apt_sury_repo }} {{ ansible_distribution_release }} main" state="present"
    - apt: update_cache=yes

- name: "Install PHP"
  apt:
    name:
      - "php{{ ledger_firefly_php_version }}"
      - "php{{ ledger_firefly_php_version }}-bcmath"
      - "php{{ ledger_firefly_php_version }}-intl"
      - "php{{ ledger_firefly_php_version }}-curl"
      - "php{{ ledger_firefly_php_version }}-zip"
      - "php{{ ledger_firefly_php_version }}-gd"
      - "php{{ ledger_firefly_php_version }}-xml"
      - "php{{ ledger_firefly_php_version }}-mbstring"
      - "php{{ ledger_firefly_php_version }}-ldap"
      - "php{{ ledger_firefly_php_version }}-pgsql"
      - "php{{ ledger_firefly_php_version }}-fpm"
      - "composer"
    state: "latest"

- name: "Add configuration for PHP-FPM"
  template:
    src: "php/www.conf.j2"
    dest: "{{ ledger_firefly_phpfpm_config_directory }}/www.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart PHP-FPM"

- name: "Start/Enable PHP-FPM"
  service:
    name: "php{{ ledger_firefly_php_version }}-fpm"
    state: "started"
    enabled: yes

- name: "Check if Firefly III has been installed"
  stat:
    path: "{{ ledger_firefly_directory }}"
  register: firefly_iii_installed

- name: "Install Firefly III"
  composer:
    command: "create-project"
    arguments: "grumpydictator/firefly-iii {{ ledger_firefly_name }} {{ ledger_firefly_version }}"
    working_dir: "{{ webserver_nginx_content_directory }}"
    no_dev: yes
    prefer_dist: yes
  when:
    - firefly_iii_installed is defined
    - firefly_iii_installed.stat.islnk is not defined

- name: "Ensure {{ ledger_firefly_directory }} permissions are set"
  file:
    path: "{{ ledger_firefly_directory }}"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    state: "directory"
    recurse: yes

- name: "Add configuration for Firefly III"
  template:
    src: "firefly/env.j2"
    dest: "{{ ledger_firefly_directory }}/.env"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    mode: "0644"

- name: "Final steps for installation"
  command: "sudo -E -u {{ webserver_nginx_user }} php artisan {{ item }}"
  args:
    chdir: "{{ ledger_firefly_directory }}"
    warn: no
  with_items:
    - "migrate:refresh --seed"
    - "firefly-iii:upgrade-database"
  when:
    - firefly_iii_installed is defined
    - firefly_iii_installed.stat.islnk is not defined

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "ledger.conf"
    credentials:
      - "htpasswd.ledger"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "ledger"
