---
- name: "Temporary directory for preparing new version of Firefly"
  tempfile: suffix="firefly" state="directory"
  register: tempdir
  notify: "Clean temporary Firefly update directory"

- name: "Update Firefly III"
  block:
    - get_url: url="{{ ledger_firefly_url }}" dest="{{ tempdir.path }}" checksum="sha256:{{ ledger_firefly_url }}.sha256"
    - file: path="{{ tempdir.path }}/{{ ledger_firefly_name }}" mode="0755" state="directory"
    - unarchive: src="{{ ledger_firefly_url }}" dest="{{ tempdir.path }}/{{ ledger_firefly_name }}" remote_src=yes exclude={{ ledger_update_unarchive_exclusions }}
    - file: path="{{ tempdir.path }}" owner="{{ webserver_nginx_user }}" group="{{ webserver_nginx_user }}" mode="0755" state="directory" recurse=yes

- name: "Add configuration for Firefly III"
  template:
    src: "firefly/env.j2"
    dest: "{{ tempdir.path }}/{{ ledger_firefly_name }}/.env"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    mode: "0644"

- name: "Copy storage and uploads from current version"
  copy:
    src: "{{ ledger_firefly_directory }}/storage"
    dest: "{{ tempdir.path }}/{{ ledger_firefly_name }}"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    remote_src: yes

- name: "Final steps for upgrade"
  command: "sudo -E -u {{ webserver_nginx_user }} php artisan {{ item }}"
  args:
    chdir: "{{ tempdir.path }}/{{ ledger_firefly_name }}"
  with_items:
    - "migrate --seed"
    - "firefly-iii:decrypt-all"
    - "cache:clear"
    - "view:clear"
    - "firefly-iii:upgrade-database"
    - "firefly-iii:laravel-passport-keys"

- name: "Enable the new version of Firefly"
  block:
    - file: path="{{ ledger_firefly_directory }}.bak" state="absent"
    - command: "mv {{ ledger_firefly_directory }} {{ ledger_firefly_directory }}.bak"
    - command: "mv {{ tempdir.path }}/{{ ledger_firefly_name }} {{ ledger_firefly_directory }}"
