---
- name: "Get currently installed version"
  command: "ledger --version"
  failed_when: no
  changed_when: no
  register: ledger_installed_version

- name: "Download and install ledger"
  block:
    - tempfile: suffix="ledger" state="directory"
      register: tempdir
    - get_url: url="{{ ledger_url }}.tar.gz" dest="{{ tempdir.path }}" checksum="sha256:{{ ledger_url }}-sha256sum.txt"
    - unarchive: src="{{ ledger_url }}.tar.gz" dest="{{ tempdir.path }}" remote_src=yes
    - command: "mv {{ tempdir.path }}/{{ ledger_filename }}/ledger {{ ledger_destination }}/ledger"
    - file: path="{{ ledger_destination }}/ledger" owner="root" group="staff"
  always:
    - file: path="{{ tempdir.path }}" state="absent"
  when: ledger_installed_version.stdout is not defined or ledger_installed_version.stdout != ledger_version_output

- name: "Create folder for ledger configuration"
  file:
    path: "{{ ledger_config_directory }}"
    owner: "{{ ledger_user }}"
    group: "{{ ledger_user }}"
    state: "directory"

- name: "Copy ledger configuration"
  template:
    src: "config.j2"
    dest: "{{ ledger_config_directory }}/config"
    owner: "{{ ledger_user }}"
    group: "{{ ledger_user }}"
    mode: "0600"

- include_role:
    name: "general"
    tasks_from: "scripts"
  with_items:
    - "bledger"
    - "nledger"
    - "rledger"
  loop_control:
    loop_var: "script"

- name: "Create user folder for systemd and for backups"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    state: "directory"
  with_items:
    - { path: "{{ ledger_backup_directory }}", owner: "{{ ledger_user }}", group: "{{ ledger_user }}" }
    - { path: "{{ systemd_directory }}", owner: "root", group: "root" }

- name: "Copy service and timer for ledger-backup"
  template:
    src: "systemd/{{ item }}.j2"
    dest: "{{ systemd_directory }}/{{ item }}"
    mode: "0600"
  with_items:
    - "ledger.service"
    - "ledger.timer"
    - "ledger-backup.service"
    - "ledger-backup.timer"
    - "ledger-networth.service"
    - "ledger-networth.timer"
    - "ledger-sync.service"
    - "ledger-sync.timer"
  notify:
    - "Restart ledger timer"
    - "Restart ledger-backup timer"
    - "Restart ledger-networth timer"
    - "Restart ledger-sync timer"

- name: "Enable/start ledger related timers"
  systemd:
    name: "{{ item }}"
    state: "started"
    enabled: yes
    daemon_reload: yes
  with_items:
    - "ledger.timer"
    - "ledger-backup.timer"
    - "ledger-networth.timer"
    - "ledger-sync.timer"
