---
- name: "Create {{ ledger_user }} user"
  user:
    name: "{{ ledger_user }}"
    home: "{{ ledger_home }}"
    shell: "/bin/false"
    state: "present"

- import_tasks: ledger.yml
- import_tasks: postgresql.yml
- import_tasks: firefly.yml

- import_tasks: firefly_update.yml
  when: update is defined and update
