---
- name: "Install python3 and pip3 and other dependencies"
  apt:
    name:
      - "python3"
      - "python3-pip"
      - "ffmpeg"
      - "pipx"
    state: "latest"

- name: "Create {{ gallery_sigal_user }} user"
  user:
    name: "{{ gallery_sigal_user }}"
    shell: "/bin/false"
    home: "{{ gallery_sigal_home }}"
    state: "present"

- name: "Install Sigal"
  community.general.pipx:
    name: "sigal"
    state: "latest"

- name: "Create Sigal configuration directory"
  file:
    path: "{{ gallery_sigal_config_directory }}"
    owner: "{{ gallery_sigal_user }}"
    group: "{{ gallery_sigal_user }}"
    mode: "0755"
    state: "directory"

- name: "Copy favicon.ico"
  copy:
    src: "favicon.ico"
    dest: "{{ gallery_sigal_home }}/favicon.ico"
    owner: "{{ gallery_sigal_user }}"
    group: "{{ gallery_sigal_user }}"

- name: "Copy Sigal settings"
  template:
    src: "sigal/sigal.conf.py.j2"
    dest: "{{ gallery_sigal_config_directory }}/sigal.conf.py"
    owner: "{{ gallery_sigal_user }}"
    group: "{{ gallery_sigal_user }}"
    mode: "0644"

- name: "Copy Sigal systemd"
  template:
    src: "sigal/sigal.service.j2"
    dest: "{{ systemd_directory }}/sigal.service"
    mode: "0644"

- name: "Reload Systemd"
  systemd:
    name: "sigal"
    daemon_reload: yes

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "process-photos"
