---
- name: "install python3 and pip3"
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "python3"
    - "python3-pip"

- name: "create {{ gallery_sigal_user }} user"
  user:
    name: "{{ gallery_sigal_user }}"
    shell: "/bin/false"
    state: "present"
    create_home: no

- name: "install Sigal"
  pip:
    name: "sigal"
    state: "latest"
    executable: "pip3"
  notify: "restart Sigal"

- name: "create Sigal configuration directory"
  file:
    path: "{{ item }}"
    owner: "{{ gallery_sigal_user }}"
    group: "{{ gallery_sigal_user }}"
    mode: "0755"
    state: "directory"
  with_items:
    - "{{ gallery_sigal_config_directory }}"
    - "{{ gallery_sigal_pictures_directory }}"

- name: "copy Sigal settings"
  template:
    src: "sigal/sigal.conf.py.j2"
    dest: "{{ gallery_sigal_config_directory }}/sigal.conf.py"
    owner: "{{ gallery_sigal_user }}"
    group: "{{ gallery_sigal_user }}"
    mode: "0644"
  notify: "restart Sigal"

- name: "copy Sigal systemd"
  template:
    src: "sigal/sigal.service.j2"
    dest: "{{ systemd_directory }}/sigal.service"
    mode: "0644"
  notify: "restart Sigal"

- name: "start/Enable Sigal"
  systemd:
    name: "sigal"
    state: "started"
    enabled: yes
    daemon_reload: yes

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "process-photos"

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "gallery.conf"
    credentials: "htpasswd.gallery"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "gallery"
