---
- name: "install Dovecot"
  apt:
    name:
      - "dovecot-core"
      - "dovecot-common"
      - "dovecot-imapd"
    default_release: "{{ ansible_distribution_release }}-backports"
    state: "latest"

- name: "check if certificate already exists"
  stat:
    path: "{{ webserver_letsencrypt_config_directory }}/live/{{ server }}/cert.pem"
  register: letsencrypt_cert

- name: "copy Dovecot settings"
  template:
    src: "dovecot/{{ item }}.j2"
    dest: "{{ email_dovecot_config_directory }}/conf.d/{{ item }}"
    mode: "0644"
  with_items:
    - "01-main.conf"
    - "10-auth.conf"
    - "10-mail.conf"
    - "10-ssl.conf"
    - "15-mailboxes.conf"
    - "auth-system.conf.ext"
  notify: "reload Dovecot"

- name: "copy Dovecot credentials"
  template:
    src: "dovecot/passwd.db.j2"
    dest: "{{ email_dovecot_config_directory }}/passwd.db"
    mode: "0644"
  notify: "reload Dovecot"

- name: "start/Enable Dovecot"
  systemd:
    name: "dovecot"
    state: "started"
    enabled: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "dovecot"
