---
- name: "Create {{ email_user }} user"
  user:
    name: "{{ email_user }}"
    uid: "{{ email_user_uid }}"
    home: "{{ email_directory }}"
    state: "present"

- import_tasks: "sieve.yml"

- block:
    - import_tasks: "opendkim.yml"
    - import_tasks: "spamassassin.yml"
    - import_tasks: "mta_sts.yml"
    - import_tasks: "postfix.yml"
    - import_tasks: "dovecot.yml"
    - import_tasks: "pflogsumm.yml"
  when: sieve is not defined or not sieve
