---
- name: "copy {{ mapping }}"
  template:
    src: "postfix/{{ mapping }}.j2"
    dest: "{{ email_postfix_config_directory }}/{{ mapping }}"
    mode: "0644"
  register: template_mapping

- name: "hash {{ mapping }}"
  command: "postmap {{ email_postfix_config_directory }}/{{ mapping }}"
  notify: "reload Postfix"
  when:
    - template_mapping is defined
    - template_mapping.changed
