---
- name: "install Pflogsumm and dependencies"
  apt:
    name:
      - "pflogsumm"
      - "procmail"
    state: "latest"

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "ppflogsumm"

- name: "copy Pflogsumm systemd"
  template:
    src: "pflogsumm/{{ item }}.j2"
    dest: "{{ systemd_directory }}/{{ item }}"
    mode: "0755"
  with_items:
    - "pflogsumm.service"
    - "pflogsumm.timer"
  notify: "restart Pflogsumm"

- name: "restart/Enable Pflogsumm"
  systemd:
    name: "pflogsumm.timer"
    state: "started"
    enabled: yes
    daemon_reload: yes
