---
- name: "Install Postfix"
  apt:
    name:
      - "postfix"
      - "ssl-cert"
    state: "latest"

- name: "Add user postfix to group opendkim"
  user:
    name: "{{ email_postfix_user }}"
    groups: "{{ email_opendkim_user }}"
    append: yes
    state: "present"

- name: "Copy mailname file"
  template:
    src: "postfix/mailname.j2"
    dest: "/etc/mailname"
    mode: "0644"
  notify: "Reload Postfix"

- name: "Check if certificate already exists"
  stat:
    path: "{{ webserver_letsencrypt_config_directory }}/live/{{ server }}/cert.pem"
  register: letsencrypt_cert

- name: "Copy Postfix settings"
  template:
    src: "postfix/{{ item }}.cf.j2"
    dest: "{{ email_postfix_config_directory }}/{{ item }}.cf"
    mode: "0644"
  with_items:
    - "main"
    - "master"
  notify: "Reload Postfix"

- include_tasks: "mapping.yml"
  with_items:
    - "virtual-mailbox-domains"
    - "virtual-mailbox-users"
    - "virtual"
    - "virtual-regex"
    - "check_access"
  loop_control:
    loop_var: "mapping"

- name: "Copy dh.pem"
  copy:
    src: "dh.pem"
    dest: "{{ email_postfix_config_directory }}/dh.pem"
    mode: "0644"
  notify: "Reload Postfix"

- name: "Start/Enable Postfix"
  systemd:
    name: "postfix"
    state: "started"
    enabled: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "postfix"
