---
netdata_url: "https://my-netdata.io/kickstart.sh"
netdata_checksum: "sha256:515ae87be1b83ea01630eae2fe58d8a6c4d790e620bc33ca9ce4e2fdcf78d2bd."

netdata_config_directory: "/etc/netdata"
netdata_port: "19999"
netdata_bind_address: "127.0.0.1"
netdata_log_directory: "/var/log/netdata"
netdata_pidfile: "/var/run/netdata/netdata.pid"
