---
- name: "Install Fail2Ban"
  apt:
    name: "fail2ban"
    state: "latest"
    update_cache: yes
  become:  yes

- name: "Copy Fail2Ban settings"
  template:
    src: "jail.local.j2"
    dest: "{{ fail2ban_config_directory }}/jail.local"
    mode: "0644"
  notify:
    - "Start Fail2Ban"
    - "Reload Fail2Ban"
  become: yes

- name: "Ensure required log files exist"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0640"
    state: "touch"
  with_items:
    - { path: "{{ monit_logfile }}", owner: "root", group: "root" }
    - { path: "/var/log/mail.warn", owner: "root", group: "adm" }
    - { path: "/var/log/mail.log", owner: "root", group: "adm" }
  become: yes

- name: "Start/Enable Fail2Ban"
  systemd:
    name: "fail2ban"
    state: "started"
    enabled: yes
  become: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "fail2ban"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "fail2ban"

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "fail2ban"
