---
- name: "install Fail2Ban"
  apt:
    name: "fail2ban"
    state: "latest"

- name: "copy Fail2Ban settings"
  template:
    src: "jail.local.j2"
    dest: "{{ fail2ban_config_directory }}/jail.local"
    mode: "0644"
  notify: "reload Fail2Ban"

- name: "ensure required log files exist"
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0640"
    state: "file"
  with_items:
    - { path: "{{ monit_logfile }}", owner: "root", group: "root" }
    - { path: "/var/log/mail.warn", owner: "root", group: "adm" }
    - { path: "/var/log/mail.log", owner: "root", group: "adm" }

- name: "start/Enable Fail2Ban"
  systemd:
    name: "fail2ban"
    state: "started"
    enabled: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "fail2ban"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "fail2ban"

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "fail2ban"
