---
- name: "Install Fail2Ban and dependencies"
  apt:
    name:
      - "fail2ban"
      - "whois"
    default_release: "{{ ansible_distribution_release }}-backports"
    state: "latest"

- name: "Copy Fail2Ban settings"
  template:
    src: "jail.local.j2"
    dest: "{{ fail2ban_config_directory }}/jail.local"
    mode: "0644"
  notify: "Reload Fail2Ban"

- name: "Add extra check to postfix"
  lineinfile:
    path: "{{ fail2ban_config_directory }}/filter.d/postfix.conf"
    regexp: 'Protocol error'
    insertafter: 'VRFY'
    line: "            ^RCPT from [^[]*\\[<HOST>\\]%(_port)s: 550 5\\.5\\.1 Protocol error\\b"
  notify: "Reload Fail2Ban"

- include_tasks: "check_file.yml"
  with_items:
    - { path: "{{ monit_logfile }}", owner: "root", group: "root" }
    - { path: "/var/log/mail.log", owner: "root", group: "adm" }
  loop_control:
    loop_var: "file"

- name: "Start/Enable Fail2Ban"
  systemd:
    name: "fail2ban"
    state: "started"
    enabled: yes

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "fail2ban"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "fail2ban"

- include_role:
    name: "general"
    tasks_from: "scripts"
  vars:
    script: "fail2ban"
