---
- name: "Generate Taskd client certificates"
  command: "./generate.client {{ taskd_client_name }}"
  args:
    chdir: "{{ taskd_pki_generators }}"

- name: "Download client certificates"
  fetch:
    src: "{{ taskd_pki_generators }}/{{ item }}"
    dest: "~/"
    flat: yes
  with_items:
    - "{{ taskd_client_name }}.key.pem"
    - "{{ taskd_client_name }}.cert.pem"
    - "ca.cert.pem"

- name: "Remove client certificates"
  file:
    path: "{{ taskd_pki_generators }}/{{ item }}"
    state: "absent"
  with_items:
    - "{{ taskd_client_name }}.key.pem"
    - "{{ taskd_client_name }}.cert.pem"

- name: "Add user"
  command: "taskd add user '{{ taskd_organisation }}' '{{ taskd_client_name }}' --data {{ taskd_directory }}"
  register: taskd_added_user
  notify: "Show user details"
