---
- name: "Generate Taskd certificates"
  command: "./generate"
  args:
    chdir: "{{ taskd_pki_generators }}"

- name: "Move certificates to Taskd directory"
  command: "mv {{ taskd_pki_generators }}/{{ item }} {{ taskd_directory }}/{{ item }}"
  args:
    creates: "{{ taskd_directory }}/{{ item }}"
    removes: "{{ taskd_pki_generators }}/{{ item }}"
  with_items:
    - "client.key.pem"
    - "client.cert.pem"
    - "server.key.pem"
    - "server.cert.pem"
    - "server.crl.pem"
  notify: "Restart Taskd"

- name: "Copy CA certificate"
  command: "cp {{ taskd_pki_generators }}/ca.cert.pem {{ taskd_directory }}/ca.cert.pem"
  args:
    creates: "{{ taskd_directory }}/ca.cert.pem"
  notify: "Restart Taskd"
