---
ledger_user: "ledger"
ledger_home: "/home/{{ ledger_user }}"

ledger_config_directory: "{{ ledger_home }}/.config/ledger"

ledger_file: "{{ ledger_config_directory }}/ledger.csv"
ledger_networth: "{{ ledger_config_directory }}/networth.csv"
ledger_backup_directory: "{{ ledger_home }}/backups/ledger"
ledger_keep_days: "7"

ledger_destination: "/usr/local/bin"

ledger_currency: "EUR"
ledger_investment_categories:
  - "Investment"
ledger_transfer: "Transfer"
ledger_ignored_accounts:
  - "Vacation"
  - "Personal"

ledger_version: "1.0.1"
ledger_filename: "ledger-v{{ ledger_version }}-x86_64-unknown-linux-musl"
ledger_url: "https://github.com/cedricpim/ledger-rust/releases/download/v{{ ledger_version }}/{{ ledger_filename }}"

ledger_mariadb_root_user: "root"
ledger_mariadb_root_password: ""
ledger_mariadb_admin_user: "admin"
ledger_mariadb_admin_password: "admin"
ledger_mariadb_firefly_user: "firefly"
ledger_mariadb_firefly_password: "firefly"
ledger_mariadb_firefly_database: "fireflydb"
ledger_mariadb_admin_hosts:
  - "127.0.0.1"
  - "::1"
  - "localhost"

ledger_mariadb_config_directory: "/etc/mysql/mariadb.conf.d"
ledger_mariadb_log_directory: "/var/log/mysql"
ledger_mariadb_pidfile: "/run/mysqld/mysqld.pid"
ledger_mariadb_sockfile: "/run/mysqld/mysqld.sock"
ledger_mariadb_port: "3306"

ledger_firefly_directory: "{{ webserver_nginx_content_directory }}/firefly-iii"
ledger_firefly_version: "5.0.5"
ledger_firefly_app_key: "SomeRandomStringOf32CharsExactly"
ledger_firefly_timezone: "Europe/Amsterdam"
ledger_firefly_sender: "firefly@localhost"
ledger_firefly_phpfpm_sockfile: "/run/php/php7.3-fpm.sock"
ledger_firefly_phpfpm_config_directory: "/etc/php/7.3/fpm/pool.d"
