---
ledger_user: "ledger"
ledger_home: "/home/{{ ledger_user }}"

ledger_config_directory: "{{ ledger_home }}/.config/ledger"

ledger_file: "{{ ledger_config_directory }}/ledger.csv"
ledger_networth: "{{ ledger_config_directory }}/networth.csv"
ledger_backup_directory: "{{ ledger_home }}/backups/ledger"
ledger_keep_days: "7"

ledger_destination: "/usr/local/bin"

ledger_currency: "EUR"
ledger_investment_categories:
  - "Investment"
ledger_transfer: "Transfer"
ledger_ignored_accounts:
  - "Vacation"
  - "Personal"

ledger_version: "5.4.0"
ledger_filename: "ledger-v{{ ledger_version }}-x86_64-unknown-linux-musl"
ledger_url: "https://github.com/cedricpim/ledger-rust/releases/download/v{{ ledger_version }}/{{ ledger_filename }}"

ledger_postgresql_admin_user: "postgres"
ledger_postgresql_admin_password: "postgres"

ledger_postgresql_firefly_user: "firefly"
ledger_postgresql_firefly_password: "firefly"
ledger_postgresql_firefly_database: "fireflydb"

ledger_postgresql_version: "11"
ledger_postgresql_user: "postgres"
ledger_postgresql_port: "5432"
ledger_postgresql_config_directory: "/etc/postgresql/{{ ledger_postgresql_version }}/main"
ledger_postgresql_data_directory: "/var/lib/postgresql/{{ ledger_postgresql_version }}/main"
ledger_postgresql_log_directory: "/var/log/postgresql"
ledger_postgresql_pidfile: "/run/postgresql/{{ ledger_postgresql_version }}-main.pid"
ledger_postgresql_sockfile: "/run/postgresql/.s.PGSQL.{{ ledger_postgresql_port }}"

ledger_firefly_name: "firefly-iii"
ledger_firefly_directory: "{{ webserver_nginx_content_directory }}/{{ ledger_firefly_name }}"
ledger_firefly_version: "5.5.1"
ledger_firefly_app_key: "SomeRandomStringOf32CharsExactly"
ledger_firefly_timezone: "Europe/Amsterdam"
ledger_firefly_sender: "firefly@localhost"
ledger_firefly_php_version: "7.4"
ledger_firefly_phpfpm_sockfile: "/run/php/php{{ ledger_firefly_php_version }}-fpm.sock"
ledger_firefly_phpfpm_config_directory: "/etc/php/{{ ledger_firefly_php_version }}/fpm"
