---
- name: "install Syncthing"
  apt:
    name: "syncthing"
    default_release: "{{ ansible_distribution_release }}-backports"
    state: "latest"

- name: "create {{ syncthing_user }} user"
  user:
    name: "{{ syncthing_user }}"
    shell: "/bin/false"
    state: "present"
    create_home: no

- name: "create Syncthing folder"
  file:
    path: "{{ syncthing_config_directory }}"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
    mode: "0755"
    state: "directory"

- name: "create Syncthing service directory"
  file:
    path: "{{ systemd_directory }}/syncthing@{{ syncthing_user }}.service.d"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

- name: "override Syncthing user"
  template:
    src: "systemd/override.conf.j2"
    dest: "{{ systemd_directory }}/syncthing@{{ syncthing_user }}.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "restart Syncthing"

- name: "start/Enable Syncthing"
  systemd:
    name: "syncthing@{{ syncthing_user }}"
    state: "started"
    enabled: yes
    daemon_reload: yes

- name: "wait until the file {{ syncthing_config_directory }}/config.xml is present"
  wait_for:
    path: "{{ syncthing_config_directory }}/config.xml"
    state: "present"

- name: "update Syncthing port"
  lineinfile:
    path: "{{ syncthing_config_directory }}/config.xml"
    regexp: '^(\s+)<address>127\.0\.0\.1'
    line: '\1<address>127.0.0.1:{{ syncthing_port }}</address>'
    backrefs: yes
  notify: "restart Syncthing"

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "sync.conf"
    credentials: "htpasswd.sync"

- include_role:
    name: "nginx"
    tasks_from: "configure"
  vars:
    conf: "personal.conf"
    credentials: "htpasswd.personal"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "sync"
