---
- name: "Add release PGP keys for Syncthing"
  apt_key:
    url: "https://syncthing.net/release-key.txt"
    state: "present"

- name: "Add source for Syncthing"
  apt_repository:
    repo: "deb http://apt.syncthing.net/ syncthing stable"
    state: "present"

- name: "Install Syncthing"
  apt:
    name: "syncthing"
    state: "latest"

- name: "Create {{ syncthing_user }} user"
  user:
    name: "{{ syncthing_user }}"
    shell: "/bin/false"
    home: "{{ syncthing_home }}"
    state: "present"

- name: "Create Syncthing configuration directory"
  file:
    path: "{{ syncthing_config_directory }}"
    owner: "{{ syncthing_user }}"
    group: "{{ syncthing_user }}"
    mode: "0755"
    state: "directory"

- name: "Create Syncthing service directory"
  file:
    path: "{{ systemd_directory }}/syncthing@{{ syncthing_user }}.service.d"
    owner: "root"
    group: "root"
    mode: "0755"
    state: "directory"

- name: "Override Syncthing user"
  template:
    src: "systemd/override.conf.j2"
    dest: "{{ systemd_directory }}/syncthing@{{ syncthing_user }}.service.d/override.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: "Restart Syncthing"

- name: "Start/Enable Syncthing"
  systemd:
    name: "syncthing@{{ syncthing_user }}"
    state: "started"
    enabled: yes
    daemon_reload: yes

- name: "Wait until the file {{ syncthing_config_directory }}/config.xml is present"
  wait_for:
    path: "{{ syncthing_config_directory }}/config.xml"
    state: "present"

- name: "Update Syncthing port"
  lineinfile:
    path: "{{ syncthing_config_directory }}/config.xml"
    regexp: '^(\s+)<address>127\.0\.0\.1'
    line: '\1<address>127.0.0.1:{{ syncthing_port }}</address>'
    backrefs: yes
  notify: "Restart Syncthing"

- include_role:
    name: "webserver"
    tasks_from: "configure"
  vars:
    conf: "sync.conf"
    credentials:
      - "htpasswd.sync"
      - "htpasswd.personal"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "sync"
