---
- name: "Install htop"
  apt:
    name: "htop"
    state: "latest"

- name: "Copy htop configuration file"
  template:
    src: "htoprc.j2"
    dest: "/etc/htoprc"
    mode: "0644"

- name: "Update bashrc with fix for htop"
  lineinfile:
    dest: "~{{ general_user }}/.bashrc"
    line: 'alias htop="TERM=xterm htop"'
