---
- name: "Add template for http"
  template:
    src: "conf.d/letsencrypt.conf.j2"
    dest: "{{ webserver_nginx_config_directory }}/conf.d/letsencrypt.conf"
    mode: "0644"
  vars:
    https: no

- name: "Reload Nginx"
  systemd:
    name: "nginx"
    state: "reloaded"

- name: "Prepare domains"
  set_fact:
    domains: "{{ webserver_letsencrypt_domains | map('regex_replace', '^(.*)$', '\\1.' + server ) | list + [ server ] }}"

- name: "Generate certificates"
  command: "certbot certonly --noninteractive --agree-tos --email {{ webserver_letsencrypt_email }} --webroot -w {{ webserver_letsencrypt_challenge_directory }} -d {{ domains | reverse | join(',') }}"
