---
- name: "Install incron"
  apt:
    name: "incron"
    state: "latest"

- name: "Configure allow list"
  copy:
    dest: "/etc/incron.allow"
    owner: "root"
    group: "incron"
    mode: "0640"
    content: "root"
  notify: "Restart incron"

- name: "Create incron user tables"
  template:
    src: "incron/incrontab.j2"
    dest: "/var/spool/incron/root"
    owner: "root"
    group: "incron"
    mode: "0600"
  notify: "Restart incron"

- name: "Start/enable incron"
  systemd:
    name: "incron"
    state: "started"
    enabled: yes
    daemon_reload: yes
