---
- name: "Install LetsEncrypt certbot"
  apt:
    name: "python-certbot-nginx"
    default_release: "{{ ansible_distribution_release }}-backports"
    state: "latest"

- name: "Create {{ webserver_letsencrypt_challenge_directory }} directory"
  file:
    path: "{{ webserver_letsencrypt_challenge_directory }}"
    owner: "{{ webserver_nginx_user }}"
    group: "{{ webserver_nginx_user }}"
    mode: "0755"
    state: "directory"

- name: "Check if certificate already exists"
  stat:
    path: "{{ webserver_letsencrypt_config_directory }}/live/{{ server }}/cert.pem"
  register: letsencrypt_cert

- import_tasks: "generate_certificates.yml"
  when: (letsencrypt_generate_force is defined and letsencrypt_generate_force) or (letsencrypt_cert is defined and letsencrypt_cert.stat.islnk is not defined)

- name: "Add template for email server renewal"
  template:
    src: "letsencrypt/mail.sh.j2"
    dest: "{{ webserver_letsencrypt_config_directory }}/renewal-hooks/post/mail.sh"
    mode: "0755"

- name: "Add template for https"
  template:
    src: "conf.d/letsencrypt.conf.j2"
    dest: "{{ webserver_nginx_config_directory }}/conf.d/letsencrypt.conf"
    mode: "0644"
  vars:
    https: yes
  register: letsencrypt_template

- name: "Update default configuration on Nginx for SSL certificates"
  template:
    src: "conf.d/default-without-certificates.conf.j2"
    dest: "{{ webserver_nginx_config_directory }}/conf.d/default.conf"
    mode: "0644"
  register: default_template

- name: "Reload Nginx"
  systemd:
    name: "nginx"
    state: "reloaded"
  when: (default_template is defined and default_template.changed) or
        (letsencrypt_template is defined and letsencrypt_template.changed)

- name: "Start/enable certbot"
  systemd:
    name: "certbot.timer"
    state: "started"
    enabled: yes
