---
- import_tasks: "nginx.yml"
- import_tasks: "letsencrypt.yml"
  when: group_names[0] != "vagrant"

- include_role:
    name: "monit"
    tasks_from: "configure"
  vars:
    conf: "nginx"

- include_role:
    name: "logrotate"
    tasks_from: "configure"
  vars:
    conf: "nginx"
