---
gallery_sigal_user: "sigal"
gallery_sigal_config_folder: "/etc/sigal"
gallery_sigal_pictures_folder: "/var/lib/sigal"
gallery_sigal_port: "8000"
gallery_sigal_title: "Gallery"
gallery_sigal_theme: "galleria"
gallery_sigal_author: "Author"
