---
- hosts: server
  become: yes

  pre_tasks:
    - name: "Update backports apt sources"
      apt_repository:
        repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: "present"

    - name: "Update current packages"
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  roles:
    - { role: "logrotate", tags: "logrotate" }
    - { role: "nginx", tags: "nginx" }
    - { role: "letsencrypt", tags: "letsencrypt" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "netdata", tags: "netdata" }
    - { role: "dav", tags: "dav" }
    - { role: "gallery", tags: "gallery" }
    - { role: "sync", tags: "sync" }
    - { role: "rkhunter", tags: "rkhunter" }
    - { role: "fail2ban", tags: "fail2ban" }
