---
- hosts: production
  become: yes

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  pre_tasks:
    - name: "Update backports apt sources"
      apt_repository:
        repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: "present"
      tags: "always"

    - name: "Get list of users before running roles"
      command: "cut -d: -f1 /etc/passwd"
      changed_when: no
      register: pre_passwd_users
      tags: "always"

    - name: "Get list of services before running roles"
      command: "systemctl list-unit-files"
      changed_when: no
      register: pre_systemd_services
      tags: "always"

  roles:
    - { role: "dns", tags: "dns" }
    - { role: "logrotate", tags: "logrotate" }
    - { role: "webserver", tags: "webserver" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "dav", tags: "dav" }
    - { role: "gallery", tags: "gallery" }
    - { role: "sync", tags: "sync" }
    - { role: "rkhunter", tags: "rkhunter" }
    - { role: "fail2ban", tags: "fail2ban" }
    - { role: "email", tags: "email" }
    - { role: "netdata", tags: "netdata" }
    - { role: "ledger", tags: "ledger" }
    - { role: "htop", tags: "htop" }
    - { role: "task", tags: "task" }

  post_tasks:
    - name: "Get list of users after running roles"
      command: "cut -d: -f1 /etc/passwd"
      changed_when: no
      register: post_passwd_users
      tags: "always"

    - name: "Check if newaliases command exists"
      stat:
        path: "/usr/bin/newaliases"
      register: newaliases_exist
      tags: "always"

    - name: "Copy aliases"
      template:
        src: "aliases.j2"
        dest: "/etc/aliases"
        mode: "0644"
      vars:
        users: "{{ post_passwd_users.stdout_lines }}"
      register: template_aliases
      when:
        - newaliases_exist is defined and newaliases_exist.stat.islnk is defined
        - pre_passwd_users is defined and post_passwd_users is defined
        - pre_passwd_users.stdout_lines != post_passwd_users.stdout_lines
      tags: "always"

    - name: "Hash aliases"
      command: "newaliases"
      notify: "Reload Postfix"
      when: template_aliases is defined and template_aliases.changed
      tags: "always"

    - name: "Get list of services after running roles"
      command: "systemctl list-unit-files"
      changed_when: no
      register: post_systemd_services
      tags: "always"

    - name: "Remove dependencies that are no longer required"
      apt:
        autoremove: yes
      tags: "always"

    - name: "Remove useless packages from the cache"
      apt:
        autoclean: yes
      tags: "always"

  handlers:
    - name: "Reload Postfix"
      systemd:
        name: "postfix"
        state: "reloaded"
      register: postfix_service_reload
      failed_when:
        - postfix_service_reload.failed
        - not "Could not find the requested service" in postfix_service_reload.msg
