---
- hosts: server
  become: yes

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  pre_tasks:
    - name: "update backports apt sources"
      apt_repository:
        repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: "present"
      tags: "always"

    - name: "update current packages"
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
      tags: "always"

  roles:
    - { role: "logrotate", tags: "logrotate" }
    - { role: "nginx", tags: "nginx" }
    - { role: "letsencrypt", tags: "letsencrypt" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "netdata", tags: "netdata" }
    - { role: "dav", tags: "dav" }
    - { role: "gallery", tags: "gallery" }
    - { role: "sync", tags: "sync" }
    - { role: "rkhunter", tags: "rkhunter" }
    - { role: "fail2ban", tags: "fail2ban" }
    - { role: "systemon", tags: "systemon" }
    - { role: "email", tags: "email" }

  post_tasks:
    - name: "get list of users"
      command: "cut -d: -f1 /etc/passwd"
      changed_when: no
      register: passwd_users
      tags: "always"

    - name: "check is newaliases command exists"
      stat:
        path: "/usr/sbin/newaliases"
      register: newaliases_exist
      tags: "always"

    - name: "copy aliases"
      template:
        src: "aliases.j2"
        dest: "/etc/aliases"
        mode: "0644"
      register: template_aliases
      when:
        - passwd_users is defined
        - newaliases_exist is defined
        - newaliases_exist.stat.islnk is defined
      tags: "always"

    - name: "hash aliases"
      command: "newaliases"
      notify: "reload Postfix"
      when:
        - template_aliases is defined
        - template_aliases.changed
      tags: "always"

    - name: "restart Systemon"
      systemd:
        name: "systemon"
        state: "restarted"
      register: systemon_service
      failed_when:
        - systemon_service.failed
        - not "Could not find the requested service" in systemon_service.msg
      tags: "always"

    - name: "remove dependencies that are no longer required"
      apt:
        autoremove: yes
      tags: "always"

    - name: "remove useless packages from the cache"
      apt:
        autoclean: yes
      tags: "always"

  handlers:
    - name: "reload Postfix"
      systemd:
        name: "postfix"
        state: "reloaded"
      register: postfix_service_reload
      failed_when:
        - postfix_service_reload.failed
        - not "Could not find the requested service" in postfix_service_reload.msg
