---
- hosts: server

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  roles:
    - { role: "logrotate", tags: "logrotate" }
    - { role: "nginx", tags: "nginx" }
    - { role: "letsencrypt", tags: "letsencrypt" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "netdata", tags: "netdata" }
    - { role: "dav", tags: "dav" }
