---
- hosts: server

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  roles:
    - { role: "nginx", tags: "nginx" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "monit", tags: "monit" }
    - { role: "netdata", tags: "netdata" }
    - { role: "radicale", tags: "radicale" }
    - { role: "sigal", tags: "sigal" }
    - { role: "syncthing", tags: "syncthing" }
    - { role: "email", tags: "email" }
    - { role: "rkhunter", tags: "rkhunter" }
    - { role: "fail2ban", tags: "fail2ban" }
    - { role: "letsencrypt", tags: "letsencrypt" }
