---
- hosts: production
  become: yes

  vars_files:
    - "../vaulted_vars/system.yml"
    - "../group_vars/system.yml"

  pre_tasks:
    - name: "Update current packages"
      apt:
        upgrade: "yes"
        update_cache: yes
        force_apt_get: yes
      tags: "always"

  roles:
    - { role: "general", tags: "general" }
