---
- hosts: vagrant

  roles:
    - { role: "general", tags: "general" }
    - { role: "logrotate", tags: "logrotate" }
    - { role: "nginx", tags: "nginx" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "netdata", tags: "netdata" }
    - { role: "dav", tags: "dav" }
    - { role: "gallery", tags: "gallery" }
    - { role: "sync", tags: "sync" }
    - { role: "rkhunter", tags: "rkhunter" }
    - { role: "fail2ban", tags: "fail2ban" }
