---
- hosts: vagrant

  roles:
    - { role: "general", tags: "general" }
    - { role: "nginx", tags: "nginx" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "netdata", tags: "netdata" }
