---
- hosts: vagrant
  become: yes

  pre_tasks:
    - name: "Update backports apt sources"
      apt_repository:
        repo: "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
        state: "present"

    - name: "Update current packages"
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes

  post_tasks:
    - name: "Restart Systemon"
      systemd:
        name: "systemon"
        state: "restarted"

  roles:
    - { role: "general", tags: "general" }
    - { role: "logrotate", tags: "logrotate" }
    - { role: "nginx", tags: "nginx" }
    - { role: "monit", tags: "monit" }
    - { role: "keeweb", tags: "keeweb" }
    - { role: "netdata", tags: "netdata" }
    - { role: "dav", tags: "dav" }
    - { role: "gallery", tags: "gallery" }
    - { role: "sync", tags: "sync" }
    - { role: "rkhunter", tags: "rkhunter" }
    - { role: "fail2ban", tags: "fail2ban" }
    - { role: "systemon", tags: "systemon" }
