---
email_user: "vmail"
email_user_uid: "5000"
email_directory: "/var/mail/vmail"

email_postfix_user: "postfix"
email_postfix_config_directory: "/etc/postfix"
email_postfix_spool: "/var/spool/postfix"
email_postfix_rbls:
  - "zen.spamhaus.org"
  - "b.barracudacentral.org"
  - "bl.spamcop.net"

email_dovecot_config_directory: "/etc/dovecot"
email_dovecot_stats_port: "24242"
email_smtpd_sasl_path: "private/dovecot-auth"

email_opendkim_user: "opendkim"
email_opendkim_config_directory: "/etc/opendkim"
email_opendkim_sock: "opendkim/opendkim.sock"
email_opendkim_subdomain: "mail"

email_spamassassin_user: "debian-spamd"
email_spamassassin_home: "/var/lib/spamassassin"
email_spamassassin_config_directory: "/etc/spamassassin"
email_spamassassin_languages:
  - "en"
  - "fr"
email_spamassassin_locales:
  - "en"
email_spamd_pidfile: "/run/spamd.pid"

email_pflogsumm_sender: "pflogsumm@localhost"
email_pflogsumm_receiver: "root@localhost"

email_mta_sts_directory: "{{ webserver_nginx_content_directory }}/mta-sts/.well-known"
email_mta_sts:
  version: "STSv1"
  mode: "enforce"
  mx: "mail1"
  max_age: "604800"

email_geoip_config_directory: "/etc"
email_maxmind_account_id: "ACCOUNT_ID"
email_maxmind_license_key: "LICENSE_KEY"
